### ISSUE TITLE
Building of the sample-app vm failing

### ISSUE THREAD

**Issue by MikeReh** [GoogleCloudPlatform/marketplace-vm-imagebuilder#36]
Hi,
trying to get the sample-app build but the build is always failing.

The logs shows : WARNING: Google Compute Platform credentials are required for this platform
    googlecompute: +but were not found, thus the agent may have failed to start or initialize
    googlecompute: +properly.  Please consult the "Authorization" section of the documentation at
    googlecompute: +${MONITORING_AGENT_DOCS_URL} then restart the agent using:
    googlecompute: +
    googlecompute: +  sudo service ${AGENT_NAME} restart

....

Executing: /lib/systemd/systemd-sysv-install enable rsyslog
    googlecompute: Created symlink /etc/systemd/system/syslog.service → /lib/systemd/system/rsyslog.service.
    googlecompute: --> Stopping Google services...
    googlecompute: Failed to stop google-accounts-daemon.service: Unit google-accounts-daemon.service not loaded.
==> googlecompute: Deleting instance...
    googlecompute: Instance has been deleted!
==> googlecompute: Deleting disk...
    googlecompute: Disk has been deleted!
Build 'googlecompute' errored: Script exited with non-zero exit status: 5

==> Some builds didn't complete successfully and had errors:
--> googlecompute: Script exited with non-zero exit status: 5

The build gets started with 👍 
export BUCKET=@@@ my Bucket
export SOLUTION_NAME=sample-app
export SERVICE_ACCOUNT=imagebuilder
export PROJECT=@@@ my Project ID 
export KEY_FILE_PATH=$PWD/imagebuilder-service-account.json

docker run \
  -v "$PWD/packer:/packer:ro" \
  -v "$PWD/chef:/chef:ro" \
  -v "$PWD/tests:/tests:ro" \
  -v "$KEY_FILE_PATH:/service-account.json:ro" \
  -e "PROJECT=$PROJECT" \
  -e "BUCKET=$BUCKET" \
  -e "SOLUTION_NAME=$SOLUTION_NAME" \
  -e "RUN_TESTS=true" \
  -e "ATTACH_LICENSE=true" \
  -e "LICENSE_PROJECT_NAME=click-to-deploy-images" \
  -e "TESTS_CUSTOM_METADATA=google-monitoring-enable=1,google-logging-enable=1,google-c2d-startup-enable=0" \
  gcr.io/cloud-marketplace-tools/vm/imagebuilder:0.1.2

**Comment by nasmart** [comment]
I hit the same problem.

Switching from using the image from Google Container Registry to building the image from the Git repo resolved the issue.

**Comment by MikeReh** [comment]
> I hit the same problem.
> 
> Switching from using the image from Google Container Registry to building the image from the Git repo resolved the issue.

Yes, that is working for me as well. Thx
