### ISSUE TITLE
Update chef-solo to Debian 9.

### ISSUE THREAD

**Issue by wgrzelak** [GoogleCloudPlatform/marketplace-vm-imagebuilder#4]
https://github.com/GoogleCloudPlatform/marketplace-vm-imagebuilder/blob/master/scripts/packergen.py#L21-L29

**Comment by armandomiani** [comment]
Outdated. Currently on Chef 18/Debian11 version. https://github.com/GoogleCloudPlatform/marketplace-vm-imagebuilder/commit/396574b0685badfa0ad9b9e61b98cbaaf415578f
